services:
  - type: web
    name: smartkasip-crm
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "php artisan serve --host=0.0.0.0 --port=8000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      # Добавь DB_HOST, DB_USERNAME, DB_PASSWORD и другие по своей базе
